version: 0.2

env:
  variables:
    REST_IMAGE:  "official-fd-supply-rest-services"
    REST_TAG:    "latest"
    PROXY_IMAGE: "official-fd-reverse-proxy"
    PROXY_TAG:   "latest"

phases:
  install:
    commands:
      - echo "install stage beginning"
      - which apt
      - apt list --installed
      - apt-get update -y
    finally:
      - echo "install stage finishing"
  pre_build:
    commands:
      - echo "pre_build stage beginning"
      - docker images list
      - docker container list -a
    finally:
      - echo "pre_build stage finishing"
  build:
    commands:
      - echo "build stage beginning"
      - docker build src/fd_supply_services/ -t $REST_IMAGE:$REST_TAG
      - docker build src/reverse-proxy/ -t $PROXY_IMAGE:$PROXY_TAG
    finally:
      - echo "build stage finishing"
      - docker images
      - docker container list --all
  post_build:
    commands:
      - echo "post_build stage beginning"
      - docker save -o ${REST_IMAGE}-${REST_TAG}.tar $REST_IMAGE:$REST_TAG
      - docker save -o ${PROXY_IMAGE}-${PROXY_TAG}.tar $PROXY_IMAGE:$PROXY_TAG
    finally:
      - echo "post_build stage finishing"
artifacts:
  files:
    - ${REST_IMAGE}-${REST_TAG}.tar
    - ${PROXY_IMAGE}-${PROXY_TAG}.tar
  discard-paths: yes
  base-directory: .

