version: 0.2

env:
  variables:
    envkey: "value"

phases:
  install:
    commands:
      - echo "install stage beginning"
      - yum update -y
      - rpm -qa
    finally:
      - echo "install stage finishing"
  pre_build:
    commands:
      - echo "pre_build stage beginning"
    finally:
      - echo "pre_build stage finishing"
  build:
    commands:
      - echo "build stage beginning"
    finally:
      - echo "build stage finishing"
  post_build:
    commands:
      - echo "post_build stage beginning"
    finally:
      - echo "post_build stage finishing"
artifacts:
  files:
    - test.tgz
  discard-paths: yes
  base-directory: .

