version: 0.2

env:
  variables:
    envkey: "value"

phases:
  install:
    commands:
      - echo "install stage beginning"
      - which apt
      - apt list --installed
      - apt-get update -y
    finally:
      - echo "install stage finishing"
  pre_build:
    commands:
      - echo "pre_build stage beginning"
      - docker images list
      - docker container list -a
    finally:
      - echo "pre_build stage finishing"
  build:
    commands:
      - echo "build stage beginning"
      - docker build src/fd_supply_services/ -t "official-fd-supply-rest-services:latest"
      - docker build src/reverse-proxy/
    finally:
      - echo "build stage finishing"
      - docker images
      - docker container list --all
  post_build:
    commands:
      - echo "post_build stage beginning"
    finally:
      - echo "post_build stage finishing"
artifacts:
  files:
    - test.tgz
  discard-paths: yes
  base-directory: .

