version: '3'

services:
  supply-db:
    image: supply-db
    environment:
      POSTGRES_DB: local_fd_supply_db
      POSTGRES_USER: local_fd_supply_db_user
      POSTGRES_PASSWORD: local_fd_supply_db_password
      PGDATA: /data/postgres-data
    build:
      context: ./supply-db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres-data
      - postgres-db-dumps:/data/postgres-db-dumps
    networks:
      localbridgenetwork:
        aliases:
          - local-dev-supply-db.internal.com

  supply-rest-service:
    image: supply-rest-service
    environment:
      - DEPLOYMENT_TYPE=DEV-LOCAL
      # - DEPLOYMENT_TYPE=DEV-REMOTE
      # - DEPLOYMENT_TYPE=PRODUCTION
    build:
      context: ./fd_supply_services
      dockerfile: Dockerfile
      args:
        - buildnumber
        - gitcommithash
    volumes:
     - ./fd_supply_services:/opt/fd-supply-services
    ports:
      - "80:80"
    depends_on:
      - supply-db
    networks:
      localbridgenetwork:
        aliases:
          - supply-rest-service.internal.com

  fd-reverse-proxy:
    hostname: $HOSTNAME
    image: fd-reverse-proxy
    environment:
      - DEPLOYMENT_TYPE=DEV-LOCAL
      # - DEPLOYMENT_TYPE=DEV-REMOTE
      # - DEPLOYMENT_TYPE=PRODUCTION
      # - REVERSE_PROXY_FQDN=FARNSWORTH.dev.SIMpkins.CLOUd
      # - SUPPLY_SERVICE_FQDN=supply-rest-service.internal.com
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
      args:
        - buildnumber
        - gitcommithash
    volumes:
     - ./reverse-proxy:/opt/reverse-proxy
    ports:
      - "443:443"
    depends_on:
      - supply-rest-service
    networks:
      localbridgenetwork:
        aliases:
          - reverse-proxy.internal.com

        #  healthcheck:
        #    test: ["CMD", "curl", "-f", "http://localhost"]
        #    interval: 1m30s
        #    timeout: 10s
        #    retries: 3
        #    start_period: 40s
        #

volumes:
  postgres-data:
  postgres-db-dumps:

networks:
  localbridgenetwork:
    driver: bridge

