version: '3'

services:
  supply-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres-data
    volumes:
      - postgres-data:/data/postgres-data
      - postgres-db-dumps:/data/postgres-db-dumps
    networks:
      localbridgenetwork:
        aliases:
          - supply-db
          - supply-db.internal.com

  supply-rest-service:
    image: supply-rest-service
    build:
      context: ./fd_supply_services
      dockerfile: Dockerfile-supply-rest-services
      args:
        - buildnumber
        - gitcommithash
    command: ./fd_supply_services/start-web-container.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - supply-db
    networks:
      localbridgenetwork:
        aliases:
          - supply-rest-service.internal.com

  fd-reverse-proxy:
    image: fd-reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
      args:
        - buildnumber
        - gitcommithash
    ports:
      - "443:443"
    depends_on:
      - supply-rest-service
    networks:
      localbridgenetwork:
        aliases:
          - reverse-proxy.internal.com

        #  healthcheck:
        #    test: ["CMD", "curl", "-f", "http://localhost"]
        #    interval: 1m30s
        #    timeout: 10s
        #    retries: 3
        #    start_period: 40s
        #

volumes:
  postgres-data:
  postgres-db-dumps:

networks:
  localbridgenetwork:
    driver: bridge

