
database:

  # note: changing these values will require you to delete the local postgres
  # data volume. Assuming you have been using docker compose, you can delete it
  # by using these commands:
  #
  # [ec2-user@bender src]$ docker-compose down
  # [ec2-user@bender src]$ docker volume ls
  # [ec2-user@bender src]$ docker volume rm src_postgres-data
  #

  description: Production database settings to connect to RDS
  engine: django.db.backends.postgresql
  port: 5432

# disable debug mode in production
debug: False
